{% set name = "dragonflye" %}
{% set version = "1.0.6" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  noarch: generic

source:
  url: https://github.com/rpetit3/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 038dac9f4b5a0cece40ff1bcc1bf0cadafb168dadb2d56f85aca683e906944b9

requirements:
  run:
    - assembly-scan >=0.4.0
    - any2fasta
    - flye
    - kmc >=3.1
    - medaka
    - miniasm
    - nanoq
    - perl
    - perl-file-spec
    - perl-findbin
    - pigz
    - racon
    - rasusa
    - raven-assembler
    - seqtk >=1.3

test:
  commands:
    - dragonflye --version | grep -F '{{ version }}'
    - dragonflye --check

about:
  home: https://github.com/rpetit3/{{ name }}
  license: GPL2
  license_file: LICENSE
  summary: Microbial assembly pipeline for Nanopore reads

extra:
  identifiers:
    - biotools:{{ name }}
    - usegalaxy-eu:{{ name }}
